spring.application.name=E-Commerce-Shopping-Cart
server.port=8080
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

#DataSource Configuration for SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=E_COMMERCE_FINAL;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123

#JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# File Upload Configuration
app.upload.dir=src/main/resources/static/images/

